### ISSUE TITLE
UserTokens Removed

### ISSUE THREAD

**Issue by ghost** [rustd/AspnetIdentitySample#15]
I have a copy of the DB generated using the Oct 3rd nightly build and noticed that the RTM and even the new nightly builds no longer have the AspNetUserTokens table. Has that functionality been removed, and will it be replaced?

The Identity implementation still feels very incomplete, and there's so little documentation, it's difficult to tell what features it really offers. The best I can find is on StackOverflow.

http://stackoverflow.com/questions/19539579/how-to-implement-a-tokenprovider-in-asp-net-identity-1-1-nightly-build

**Comment by rustd** [comment]
Please go to asp.net/identity for more documentation and the feature set. We are writing more docs. THe UserToens functionality will be added in 1.1

**Comment by rustd** [comment]
PasswordReset and account confirmation are now supported in 2.0.0-alpha1. More details are http://blogs.msdn.com/b/webdev/archive/2013/12/20/announcing-preview-of-microsoft-aspnet-identity-2-0-0-alpha1.aspx
