### ISSUE TITLE
UserManager.Users and RoleManager.Roles can not be resolved.

### ISSUE THREAD

**Issue by jrswenson** [rustd/AspnetIdentitySample#16]
Are these extension that I'm missing?  Or were these possibly removed?

There are also problems with the nuget packages for Microsoft.AspNet.Identity and Microsoft.Owin where they would not restore or update.  Editing the packages.config file fixed that.

Once I get past the problem with Users and Roles, I'd be happy to commit the changes for the packages...

**Comment by rustd** [comment]
Please do send a pull request. My guess is that the problem would be in using the 1.1 version of the packages from the Nightly feed? can you please check

**Comment by garyepaul** [comment]
I got the latest packages and no longer have the issue with RoleManager.Roles Now I start up and go to Register, as soon as I click in any field I get this: Unhandled exception at line 1152, column 5 in http://localhost:26755/scripts/jquery.validate.js 0x800a138f - JavaScript runtime error: Unable to get property 'call' of undefined or null reference. Any guidance??
![capture](https://f.cloud.github.com/assets/577037/1414747/8a75dcf0-3ea5-11e3-9570-24908431d1bd.PNG)

**Comment by rustd** [comment]
please update to the latest version of jquery.validation. Someone else reported this but I was unable to repro this on my own box

**Comment by VintageInput** [comment]
I am creating my own asp.net Identity project and I am having a problem with my RoleManager object. I don't appear to have access to the methods in the RoleStore class for deleting roles, via my RoleManager object. Is this feature only available in the nuget pre-release packages, or am I missing something?  Is there another way to go about deleting roles?

**Comment by rustd** [comment]
This feature is available in 2.0.0-alpha1 preview of ASP.NET Identity. I have updated the sample for this
