### ISSUE TITLE
Use int ID

### ISSUE THREAD

**Issue by leo-mck** [rustd/AspnetIdentitySample#18]
I am migrating from SimpleMembership and my Users table has ID as INT and all tables use it as FK. Is it possible to change the Id type to be int (and a identity field)?

**Comment by Webdiyer** [comment]
I'd like to know too!

**Comment by rustd** [comment]
Yes, this is possible in the 2.0.0-alpha1 preview we just released. More information about this release http://blogs.msdn.com/b/webdev/archive/2013/12/20/updating-asp-net-applications-from-asp-net-identity-1-0-to-2-0-0-alpha1.aspx
You can find a sample here https://aspnet.codeplex.com Look under Samples folder for Identity
