### ISSUE TITLE
Please update sample app

### ISSUE THREAD

**Issue by boomer57** [rustd/AspnetIdentitySample#19]
The RTM package versions are now released, but this Aspnet Identity app still has dependencies to alpha version pkgs, so please update it to the released version. Thank you.

**Comment by JoshSimerman** [comment]
The Alpha references are to the nightly builds in use. Notice the nightly version is greater than the RTM version numbers.

**Comment by boomer57** [comment]
Hi,

I was getting compilation errors when I downloaded the project and ran it in VS 2013 Professional, and they were due to references failures to ALPHA versions referenced in the NuGet Package.Config. 

I then did the NuGet update all to get v4.5.1 versions of as many components as possible, and that helped eliminate those missing packages and references errors, but I then got a 17 compile errors after going with the gold RTM versions of the references.

I have not yet overcome that hurdle. 

This has been pretty painful for what is supposed to be a Getting Started kind of application.

It seems to me - now that VS 2013 is out - going with the RTM version would be the best option for distribution to your audience of folks not yet familiar with ASP.Net Identity. 

All I want is a download sample app that compiles cleanly in VS 2013 the first time.

Anything you can do to help would be appreciated.

Thanks!

**Comment by rustd** [comment]
I have updated the sample to pull in the latest pre release version
