### ISSUE TITLE
CreateAndSignInExternalUser problem

### ISSUE THREAD

**Issue by nonintanon** [rustd/AspnetIdentitySample#2]
This line always return false and redirect to View("ExternalLoginFailure")

``` C#
AuthenticationManager.CreateAndSignInExternalUser(HttpContext, model.LoginProvider, new User(model.UserName)))
```

Do I need .NET 4.5.1 Preview installed?

**Comment by alexsandro-xpt** [comment]
Good question, it's need .NET 4.5.1 Preview installed?

**Comment by rustd** [comment]
You do not need .NET 4.5.1 Preview for this sample. All the references are pulled in via the NuGet packages

**Comment by alexsandro-xpt** [comment]
Another question, do you want to do a Unit test project to test ASP.net Identity integration? It's will be awesome.

**Comment by gplesz** [comment]
@nonintanon: Can you try this: #4? Does not solve your problem?

**Comment by rustd** [comment]
I checked merged the pull request and checkied in the changes along with updating the sample to RC1
