### ISSUE TITLE
Can't install Microsoft.AspNet.Identity.Core version 1.1.0-alpha1-130930

### ISSUE THREAD

**Issue by sargin48** [rustd/AspnetIdentitySample#21]
i can't install unavailable references.

Install-Package Microsoft.AspNet.Identity.Core –IncludePrerelease –version 1.1.0-
alpha1-130930

-- Message : Unable to find version '1.1.0-alpha1-130930' of package 'Microsoft.AspNet.Identity.Core'.

And other unavailable references..
Img : http://r1311.hizliresim.com/1h/q/usfkc.png

Please help..

**Comment by nd4c** [comment]
I've have the same problem...  Tried uninstalling and reinstalling different packages - nothing worked.

**Comment by JoshSimerman** [comment]
The 130930 in the package name is a date, which is pretty old by now, so it's probably no longer available for download as a nightly build. First, you need to add the myget repo as a package source. You'll need to update those packages manually to trigger the newest nightly to download. The code has changed as well, so you may have compile errors.

**Comment by nd4c** [comment]
Josh,  thanks.  I was able to get all the packages sorted out and updated to the latest nightly build.  The solution compiles but I now get a runtime error: 
Could not load file or assembly 'System.Web.Mvc, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Note that I'm using VS Express 2013 for Web.  Do I have to have a nightly build of VS as well?

**Comment by nd4c** [comment]
I searched both "Could not load file or assembly 'System.Web.Mvc" (typically an unprepared server) and "The located assembly's manifest definition does not match the assembly reference."  but I have no idea how to figure out what assembly it's referring to and what to do about...

**Comment by nd4c** [comment]
Ok - found it.  I have Mvc 5.1 so I had to update Web.config.  Up and Running!

**Comment by rustd** [comment]
I have updated this packages in this sample to depend upon the latest pre-release versions
