### ISSUE TITLE
How Solve problems with packages, Solution HERE

### ISSUE THREAD

**Issue by matpag** [rustd/AspnetIdentitySample#22]
All the problems, like compiling errors are caused by wrong packages version, i've done many trials and i finally found the solutions for make this example work, open packages.config and use NuGet packages until you have these packages version in your project

  package id="Antlr" version="3.5.0.2" targetFramework="net45"
  package id="bootstrap" version="3.0.0" targetFramework="net45"
  package id="EntityFramework" version="6.1.0-alpha1-21125" targetFramework="net45"
  package id="jQuery" version="2.0.3" targetFramework="net45"
  package id="jQuery.Validation" version="1.8.1" targetFramework="net45"
  package id="Microsoft.AspNet.Identity.Core" version="2.0.0-alpha1-131218" targetFramework="net45"
  package id="Microsoft.AspNet.Identity.EntityFramework" version="2.0.0-alpha1-131218" targetFramework="net45"
  package id="Microsoft.AspNet.Identity.Owin" version="1.0.0" targetFramework="net45"
  package id="Microsoft.AspNet.Mvc" version="5.0.0-rc1" targetFramework="net45"
  package id="Microsoft.AspNet.Razor" version="3.0.0-rc1" targetFramework="net45"
  package id="Microsoft.AspNet.Web.Optimization" version="1.1.0" targetFramework="net45"
  package id="Microsoft.AspNet.WebPages" version="3.0.0-rc1" targetFramework="net45"
  package id="Microsoft.jQuery.Unobtrusive.Ajax" version="3.0.0-rc1" targetFramework="net45"
  package id="Microsoft.jQuery.Unobtrusive.Validation" version="3.0.0-rc1" targetFramework="net45"
  package id="Microsoft.Owin" version="2.1.0-rtw-21218-737-dev" targetFramework="net45"
  package id="Microsoft.Owin.Host.SystemWeb" version="2.0.2" targetFramework="net45"
  package id="Microsoft.Owin.Security" version="2.1.0-rtw-21218-737-dev" targetFramework="net45"
  package id="Microsoft.Owin.Security.Cookies" version="2.1.0-rc1" targetFramework="net45"
  package id="Microsoft.Owin.Security.Facebook" version="2.0.2" targetFramework="net45"
  package id="Microsoft.Owin.Security.Google" version="2.0.2" targetFramework="net45"
  package id="Microsoft.Owin.Security.MicrosoftAccount" version="2.0.2" targetFramework="net45"
  package id="Microsoft.Owin.Security.OAuth" version="2.1.0-rc1" targetFramework="net45"
  package id="Microsoft.Owin.Security.Twitter" version="2.0.2" targetFramework="net45"
  package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45"
  package id="Modernizr" version="2.6.2" targetFramework="net45"
  package id="Newtonsoft.Json" version="5.0.8" targetFramework="net45"
  package id="Owin" version="1.0" targetFramework="net45"
  package id="WebGrease" version="1.5.2" targetFramework="net45"

UPDATED TO 19/12/2013 (Remember to include Prerelease version of packages)
Hope could solve problems for you
Thanks to the creator of this project :)

**Comment by rustd** [comment]
I have updated this sample to the latest stable versions and update the code as well
