### ISSUE TITLE
Unhandled exception when trying to Register or Log In

### ISSUE THREAD

**Issue by bob-2165** [rustd/AspnetIdentitySample#23]
Hi,

I am trying to Run this application in IE, however when I try to Register as a new user or Log In I keep getting this message:

Unhandled exception at line 1152, column 5 in http://localhost:26755/Scripts/jquery.validate.js

0x800a138f - JavaScript runtime error: Unable to get property 'call' of undefined or null reference

How do I avoid this error?

**Comment by rustd** [comment]
What version of IE browser are you using? Can you update jquery and see if that fixes it?

**Comment by bob-2165** [comment]
Hi,

I am using the most recent version of ie with vs 2013 pro. I ran the project from your most recent update.

**Comment by cjaques** [comment]
Hey Bobbi, 

My guess is that you have an old version of JQuery.Validation.
Try typing "Update-Package jQuery.Validation" under the package manager console.

Then, make sure you are using the last version of IE or another web browser.

Let us know if it helped, good luck

**Comment by bob-2165** [comment]
I will try it out.  I am using Visual Studio Pro 2013, so I'd assume I have the latest version.

**Comment by ledpup** [comment]
Are you using IE11? I dropped back to jQuery 1.11 and switched to Chrome and it works.

**Comment by bob-2165** [comment]
Ok, I figured it out. I updated jQuery and jQuery.Validation in the Package Manager Console like you said and voila it works.

Thank you.
