### ISSUE TITLE
Missing MyUser class

### ISSUE THREAD

**Issue by jsupriyanto** [rustd/AspnetIdentitySample#25]
CS0234: The type or namespace name 'MyUser' does not exist in the namespace 'AspnetIdentitySample.Models' (are you missing an assembly reference?)public class _Page_Views_UsersAdmin_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<AspnetIdentitySample.Models.MyUser>> {

**Comment by piresio** [comment]
jsupriyanto as workaround I realized the call the following class "Microsoft.AspNet.Identity.EntityFramework.IdentityUser" in place of the current "AspnetIdentitySample.Models.MyUser".

**Comment by ctolkien** [comment]
I think the idea is that you inherit from IdentityUser with your own User class.

**Comment by rustd** [comment]
Thank you for submitting the pull requests jsupriyanto. I have merged them into the sample
