### ISSUE TITLE
Customized Membership fails at local registration

### ISSUE THREAD

**Issue by VitoDeCarlo** [rustd/AspnetIdentitySample#3]
With very little documentation available so far, on the Microsoft.AspNet.Identity classes, I've tried to create a customized membership system without any luck.  I've simplified my code, which is posted at StackOverflow (URL below), but it's failing at registering a local user.  I can't figure out why.  If you could post, either there or here, and give me some assistance, I would appreciate it.

http://stackoverflow.com/questions/17911430/custom-membership-with-microsoft-aspnet-identity-createlocaluser-fails

I can't wait for more documentation to start showing up.  Thanks for any help you can provide.

-Vito

**Comment by rustd** [comment]
Does this still repro for you?

**Comment by VitoDeCarlo** [comment]
Yes, I gave up on customizing the authentication process, as I was told that Microsoft of rewriting it for the release to allow for the type of customizations that I want to do.

**Comment by rustd** [comment]
The RC1 packages were just released which should have the fix. Can you please give those a try?

**Comment by rustd** [comment]
Please reopn this bug if the issue still reproes
