### ISSUE TITLE
change table name from pure web api application

### ISSUE THREAD

**Issue by handoyo** [rustd/AspnetIdentitySample#31]
Hi,first of all thanks for the great sample.i would likesss to ask if it's possible to implement changing aspnetusers table name and add fields.thanks a lot. :)

**Comment by rustd** [comment]
Thanks and most welcome. Yes it is possible to change the table name. You can look in the Models folder /Models/AppModel.cs and see how to add more properties to the User model and change the table name

**Comment by handoyo** [comment]
Hi,i've tried according appmodel.cs,it still creates aspnetuser table.Is it ok with you if i send the code to you?thanks

**Comment by rustd** [comment]
yes you can send me your code

**Comment by handoyo** [comment]
What is your email?or where should i send it to?thanks

**Comment by handoyo** [comment]
This is the code.Thanks
 ChristianSocial.rarhttps://docs.google.com/file/d/0B98rC3QN-4vCejJqWEVUN25XSjQ/edit?usp=drive_web

**Comment by handoyo** [comment]
Hi,did you saw my code?Sorry if i disturb you while you're busy.Thank you
