### ISSUE TITLE
How to Show all Roles in Web Forms Application?

### ISSUE THREAD

**Issue by ranaanees** [rustd/AspnetIdentitySample#34]
Hello,
I am making a form to show all Roles in the AspNetRoles table. I see how it is done in AspnetIdentitySample but not getting it work on Web Forms App. Here is how i am doing..

<code>
        private ApplicationDbContext context;
        private UserManager<ApplicationUser> manager;
        public RoleManager<IdentityRole> roleManager;
        public ApplicationUser currentUser;

```
    public UserManager<ApplicationUser> UserManager { get; private set; }
    public RoleManager<IdentityRole> RoleManager { get; private set; }

    protected string SuccessMessage
    {
        get;
        private set;
    }

    public RolesList()
    {
        context = new ApplicationDbContext();
        manager = new UserManager<ApplicationUser>(new   UserStore<ApplicationUser>(context));
        roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));

    }

    public RolesList(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
    {
        UserManager = userManager;
        RoleManager = roleManager;
    }
    protected void Page_Load(object sender, EventArgs e)
    {
        context = new ApplicationDbContext();
        roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
       GridView1.datasource = roleManager.Roles; // Roles is not availabe...
      GridView1.databinding;
    }
```

</code>

This code does not give me list of Roles to show in GridView...Need Help.

**Comment by kastimdev** [comment]
Instead of making context = new ApplicationDbContext() ... try to load it:
context = HttpContext.GetOwinContext().Get< ApplicationDbContext >();

**Comment by ranaanees** [comment]
@jopierrelerm Thanks but getting following error...
<code>
        protected void Page_Load(object sender, EventArgs e)
        {
           var context = HttpContext.GetOwinContext().Get<ApplicationDbContext>();
            roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
        }
</code>
<code>
Error   1   'System.Web.HttpContext' does not contain a definition for 'GetOwinContext' D:\Exercise\IdentityApp1\IdentityWebApplication1\Account\RolesList.aspx.cs  46  38  IdentityWebApplication1
</code>

**Comment by kastimdev** [comment]
Have you built this into the sample application or have you created own project and then added Identity with Nuget package?

**Comment by ranaanees** [comment]
Its my own separate project created in VS 2013 with 4.5.1 framework.

**Comment by kastimdev** [comment]
Perhaps you want to look at version 2 of Identity in beta now.
About > 
http://blogs.msdn.com/b/webdev/archive/2014/02/11/announcing-preview-of-microsoft-aspnet-identity-2-0-0-beta1.aspx
How to update (Referes to alpha version but you can apply it to beta version) >
http://blogs.msdn.com/b/webdev/archive/2013/12/20/updating-asp-net-applications-from-asp-net-identity-1-0-to-2-0-0-alpha1.aspx

**Comment by ranaanees** [comment]
@jopierrelerm your solution working...updated Identity to version 2. Thanks.
