### ISSUE TITLE
Getting a bunch of jquery break alerts... 

### ISSUE THREAD

**Issue by Ryanb58** [rustd/AspnetIdentitySample#43]
Running VS 2013 update 2... all I keep getting is a bunch of errors... Anyone else?

The project builds correctly. Just feels super clunky to get this working...

**Comment by Szelzz** [comment]
run `update-package` in Package Manager Console
an then in `MyClaimsIdentityFactory.cs` [add "class" keyword](https://github.com/rustd/AspnetIdentitySample/issues/36#issuecomment-39915023)

```
public class MyClaimsIdentityFactory<TUser> : ClaimsIdentityFactory<TUser> where TUser : class, IUser<string>
                                                                                         ^^^^^^
```

**Comment by Ryanb58** [comment]
Thanks a ton @Szelzz . It works great now. I didn't realize the packages and such had been updated.
