### ISSUE TITLE
Will not work on SQL Express

### ISSUE THREAD

**Issue by ghost** [rustd/AspnetIdentitySample#6]
If you take this sample and create a new database on a local SQL Express server, it fails when trying to create the database.

All I did was create an "Identity" database and change the connection string to this:

```
<add name="DefaultConnection" 
     connectionString="Data Source=.\SQLEXPRESS;Database=Identity;Integrated Security=True"
     providerName="System.Data.SqlClient" />
```

It gives an error when registering a new user:

Invalid object name 'dbo.UserSecrets'.

**Comment by rustd** [comment]
Please make sure you are running sql express and the connection string is of the correct format....http://www.connectionstrings.com/sql-server-2005 has some examples
